/**
 * Custom image loader for optimized images
 * This loader uses pre-optimized images generated by scripts/optimize-images.js
 */

export interface ImageLoaderProps {
  src: string;
  width: number;
  quality?: number;
}

export default function optimizedImageLoader({ src, width }: ImageLoaderProps): string {
  // Remove leading slash if present
  const normalizedSrc = src.startsWith('/') ? src.slice(1) : src;

  // Get file extension and base name
  const lastDot = normalizedSrc.lastIndexOf('.');
  const basePath = normalizedSrc.substring(0, lastDot);
  const ext = normalizedSrc.substring(lastDot);

  // Define available sizes per image type based on optimize-images.js output
  let availableSizes = [640, 828, 1080, 1920]; // Default (Hero images)

  if (basePath.includes('flux-1-kontext-pro')) {
    availableSizes = [147];
  } else if (
    basePath.includes('bratislava-airport') || 
    basePath.includes('budapest-airport') || 
    basePath.includes('europa-shopping') || 
    basePath.includes('polana-hotel') || 
    basePath.includes('ministry-of-fun')
  ) {
    // Partner logos
    availableSizes = [192];
  } else if (
    basePath.includes('images/processed/airport-transfer') || 
    basePath.includes('images/processed/family-transfer') || 
    basePath.includes('images/processed/car-interior') ||
    basePath.includes('images/processed/hotel-night')
  ) {
    // Service cards
    availableSizes = [640, 828, 1024, 1200];
  }

  // Find the closest available size that is >= requested width to ensure quality,
  // or the largest available if all are smaller.
  // We prefer slightly larger image over non-existent one.
  const closestSize = availableSizes.reduce((prev, curr) => {
    return (Math.abs(curr - width) < Math.abs(prev - width) ? curr : prev);
  });
  
  // Correction: If the closest size is smaller than 640 for service cards, force 640
  // because 192w doesn't exist for them.
  let finalSize = closestSize;
  
  // Specific override for service cards to avoid 404s on small sizes
  if (
    (basePath.includes('images/processed/airport-transfer') || 
     basePath.includes('images/processed/family-transfer') || 
     basePath.includes('images/processed/car-interior') ||
     basePath.includes('images/processed/hotel-night')) &&
     finalSize < 640
  ) {
    finalSize = 640;
  }

  // Check if this is an image that gets optimized
  const optimizedPaths = [
    'lexi-anderson-G8wPrJyNqWQ-unsplash',
    'flux-1-kontext-pro_a_Modern_logo_design_f',
    'images/processed/airport-transfer',
    'images/processed/family-transfer',
    'images/processed/car-interior',
    'images/processed/hotel-night',
    'images/processed/bratislava-airport',
    'images/processed/budapest-airport',
    'images/processed/europa-shopping',
    'images/processed/polana-hotel',
    'images/processed/ministry-of-fun',
    'images/processed/ministry-of-fun-white',
  ];

  const isOptimized = optimizedPaths.some(path => basePath.includes(path));

  if (!isOptimized) {
    // Return original for non-optimized images
    return `/${normalizedSrc}`;
  }

  // Build optimized path
  const pathParts = basePath.split('/');
  const fileName = pathParts[pathParts.length - 1];
  const dirPath = pathParts.slice(0, -1).join('/');

  // Use WebP format (modern browsers support it, fallback handled by Next.js)
  const optimizedPath = dirPath
    ? `/${dirPath}/optimized/${fileName}-${finalSize}w.webp`
    : `/optimized/${fileName}-${finalSize}w.webp`;

  return optimizedPath;
}