/**
 * Custom image loader for optimized images
 * This loader uses pre-optimized images generated by scripts/optimize-images.js
 */

export interface ImageLoaderProps {
  src: string;
  width: number;
  quality?: number;
}

export default function optimizedImageLoader({ src, width }: ImageLoaderProps): string {
  // Remove leading slash if present
  const normalizedSrc = src.startsWith('/') ? src.slice(1) : src;

  // Get file extension and base name
  const lastDot = normalizedSrc.lastIndexOf('.');
  const basePath = normalizedSrc.substring(0, lastDot);
  const ext = normalizedSrc.substring(lastDot);

  // Find the closest available size
  // Available sizes from optimization script: 147, 192, 640, 828, 1024, 1080, 1200, 1920
  const sizes = [147, 192, 640, 828, 1024, 1080, 1200, 1920];
  const closestSize = sizes.reduce((prev, curr) =>
    Math.abs(curr - width) < Math.abs(prev - width) ? curr : prev
  );

  // Check if this is an image that gets optimized
  const optimizedPaths = [
    'lexi-anderson-G8wPrJyNqWQ-unsplash',
    'flux-1-kontext-pro_a_Modern_logo_design_f',
    'images/processed/airport-transfer',
    'images/processed/family-transfer',
    'images/processed/car-interior',
    'images/processed/hotel-night',
    'images/processed/bratislava-airport',
    'images/processed/budapest-airport',
    'images/processed/europa-shopping',
    'images/processed/polana-hotel',
    'images/processed/ministry-of-fun',
    'images/processed/ministry-of-fun-white',
  ];

  const isOptimized = optimizedPaths.some(path => basePath.includes(path));

  if (!isOptimized) {
    // Return original for non-optimized images
    return `/${normalizedSrc}`;
  }

  // Build optimized path
  const pathParts = basePath.split('/');
  const fileName = pathParts[pathParts.length - 1];
  const dirPath = pathParts.slice(0, -1).join('/');

  // Use WebP format (modern browsers support it, fallback handled by Next.js)
  const optimizedPath = dirPath
    ? `/${dirPath}/optimized/${fileName}-${closestSize}w.webp`
    : `/optimized/${fileName}-${closestSize}w.webp`;

  return optimizedPath;
}
